[2025-01-14T19:49:30.717+0000] {processor.py:186} INFO - Started process (PID=3109) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:30.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:49:30.720+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.719+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:30.737+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:30.821+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.820+0000] {override.py:1911} INFO - Created Permission View: can read on DAG:first_dag
[2025-01-14T19:49:30.829+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.829+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG:first_dag
[2025-01-14T19:49:30.835+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.835+0000] {override.py:1911} INFO - Created Permission View: can edit on DAG:first_dag
[2025-01-14T19:49:30.845+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.844+0000] {override.py:1911} INFO - Created Permission View: menu access on DAG Run:first_dag
[2025-01-14T19:49:30.851+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.851+0000] {override.py:1911} INFO - Created Permission View: can read on DAG Run:first_dag
[2025-01-14T19:49:30.857+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.856+0000] {override.py:1911} INFO - Created Permission View: can create on DAG Run:first_dag
[2025-01-14T19:49:30.863+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.863+0000] {override.py:1911} INFO - Created Permission View: can delete on DAG Run:first_dag
[2025-01-14T19:49:30.864+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.863+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:49:30.873+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.873+0000] {dag.py:3262} INFO - Creating ORM DAG for first_dag
[2025-01-14T19:49:30.881+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:30.881+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:49:30.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.185 seconds
[2025-01-14T19:49:42.135+0000] {processor.py:186} INFO - Started process (PID=3150) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:42.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:49:42.140+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:42.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:42.162+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:42.173+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:42.173+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:49:42.191+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:42.191+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:49:42.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.082 seconds
[2025-01-14T19:49:55.069+0000] {processor.py:186} INFO - Started process (PID=3315) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:55.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:49:55.078+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:55.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:55.104+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:55.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 15
    default_args=
    ^^^^^^^^^^^^^
SyntaxError: expected argument value expression
[2025-01-14T19:49:55.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:55.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.095 seconds
[2025-01-14T19:49:57.410+0000] {processor.py:186} INFO - Started process (PID=3415) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:57.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:49:57.413+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:57.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:57.436+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:49:57.457+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:57.457+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:49:57.479+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:49:57.479+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:49:57.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.113 seconds
[2025-01-14T19:50:21.882+0000] {processor.py:186} INFO - Started process (PID=3456) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:21.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:50:21.889+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:21.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:21.911+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:21.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3
    from airflow.
                 ^
SyntaxError: invalid syntax
[2025-01-14T19:50:21.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:21.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.066 seconds
[2025-01-14T19:50:27.194+0000] {processor.py:186} INFO - Started process (PID=3691) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:27.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:50:27.197+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:27.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:27.212+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:27.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 3, in <module>
    from airflow.operators.bash import bash
ImportError: cannot import name 'bash' from 'airflow.operators.bash' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py)
[2025-01-14T19:50:27.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:27.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.040 seconds
[2025-01-14T19:50:29.391+0000] {processor.py:186} INFO - Started process (PID=3721) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:29.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:50:29.398+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:29.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:29.424+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:29.617+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:29.616+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:50:29.636+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:29.635+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:50:29.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.278 seconds
[2025-01-14T19:50:54.172+0000] {processor.py:186} INFO - Started process (PID=3762) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:54.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:50:54.177+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:54.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:54.298+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:54.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 18, in <module>
    task1
NameError: name 'task1' is not defined
[2025-01-14T19:50:54.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:54.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.157 seconds
[2025-01-14T19:50:57.911+0000] {processor.py:186} INFO - Started process (PID=3980) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:57.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:50:57.913+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:57.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:57.933+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:50:57.943+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:57.943+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:50:57.964+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:50:57.964+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:50:57.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.081 seconds
[2025-01-14T19:51:01.679+0000] {processor.py:186} INFO - Started process (PID=4027) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:01.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:01.683+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:01.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:01.712+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:01.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 19, in <module>
    task_i
NameError: name 'task_i' is not defined
[2025-01-14T19:51:01.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:01.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.068 seconds
[2025-01-14T19:51:07.725+0000] {processor.py:186} INFO - Started process (PID=4039) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:07.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:07.727+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:07.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:07.752+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:07.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 18, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-14T19:51:07.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:07.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.048 seconds
[2025-01-14T19:51:12.031+0000] {processor.py:186} INFO - Started process (PID=4074) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:12.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:12.033+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:12.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:12.052+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:12.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 18, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-14T19:51:12.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:12.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.042 seconds
[2025-01-14T19:51:20.109+0000] {processor.py:186} INFO - Started process (PID=4079) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:20.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:20.114+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:20.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:20.154+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:20.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/first_dag.py", line 18, in <module>
    task1 = BashOperator(
            ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2025-01-14T19:51:20.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:20.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.077 seconds
[2025-01-14T19:51:24.171+0000] {processor.py:186} INFO - Started process (PID=4084) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:24.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:24.173+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:24.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:24.194+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:24.282+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:24.281+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:51:24.298+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:24.298+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:51:24.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.153 seconds
[2025-01-14T19:51:43.584+0000] {processor.py:186} INFO - Started process (PID=4380) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:43.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:43.587+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:43.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:43.607+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:43.616+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:43.616+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:51:43.634+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:43.634+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:51:43.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.070 seconds
[2025-01-14T19:51:54.668+0000] {processor.py:186} INFO - Started process (PID=4385) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:54.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:54.672+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:54.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:54.696+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:54.827+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:54.826+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:51:54.845+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:54.844+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:51:54.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.203 seconds
[2025-01-14T19:51:58.674+0000] {processor.py:186} INFO - Started process (PID=4534) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:58.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:51:58.676+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:58.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:58.698+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:51:58.707+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:58.707+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:51:58.727+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:51:58.727+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:51:58.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.078 seconds
[2025-01-14T19:52:14.317+0000] {processor.py:186} INFO - Started process (PID=4686) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:52:14.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:52:14.320+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:52:14.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:52:14.347+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:52:14.360+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:52:14.360+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:52:14.383+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:52:14.383+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:52:14.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.090 seconds
[2025-01-14T19:52:32.874+0000] {processor.py:186} INFO - Started process (PID=4946) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:52:32.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:52:32.876+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:52:32.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:52:32.896+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:52:32.911+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:52:32.911+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:52:32.928+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:52:32.928+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:52:32.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.076 seconds
[2025-01-14T19:53:04.187+0000] {processor.py:186} INFO - Started process (PID=5237) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:53:04.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:53:04.189+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:53:04.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:53:04.202+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:53:04.216+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:53:04.216+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:53:04.235+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:53:04.235+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:53:04.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.072 seconds
[2025-01-14T19:53:35.587+0000] {processor.py:186} INFO - Started process (PID=5502) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:53:35.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:53:35.590+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:53:35.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:53:35.604+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:53:35.620+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:53:35.619+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:53:35.638+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:53:35.638+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-07-30 00:00:00+00:00, run_after=2021-07-31 00:00:00+00:00
[2025-01-14T19:53:35.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.073 seconds
[2025-01-14T19:54:39.953+0000] {processor.py:186} INFO - Started process (PID=5640) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:54:39.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:54:40.007+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:54:40.236+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:54:40.411+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.410+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-07-31T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:40.589+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:40.591+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.330073+00:00 end:2025-01-14 19:54:40.572953+00:00 duration:24.24288
[2025-01-14T19:54:40.592+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-07-31 00:00:00+00:00: scheduled__2021-07-31T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:38.779558+00:00. externally triggered: False>
[2025-01-14T19:54:40.593+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-07-31T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:40.594+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.594+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-07-31T00:00:00+00:00, execution_date=20210731T000000, start_date=20250114T195416, end_date=20250114T195440
[2025-01-14T19:54:40.653+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.653+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-07-31T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:40.657+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.657+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-03T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:40.684+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:40.684+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.332003+00:00 end:2025-01-14 19:54:40.683645+00:00 duration:24.351642
[2025-01-14T19:54:40.685+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-03 00:00:00+00:00: scheduled__2021-08-03T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:38.954552+00:00. externally triggered: False>
[2025-01-14T19:54:40.685+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-03T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:40.686+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.685+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-03T00:00:00+00:00, execution_date=20210803T000000, start_date=20250114T195416, end_date=20250114T195440
[2025-01-14T19:54:40.695+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.695+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-03T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:40.698+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.698+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-01T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:40.711+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:40.712+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.330021+00:00 end:2025-01-14 19:54:40.710843+00:00 duration:24.380822
[2025-01-14T19:54:40.712+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-01 00:00:00+00:00: scheduled__2021-08-01T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:38.834816+00:00. externally triggered: False>
[2025-01-14T19:54:40.713+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-01T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:40.713+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.713+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-01T00:00:00+00:00, execution_date=20210801T000000, start_date=20250114T195416, end_date=20250114T195440
[2025-01-14T19:54:40.721+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.721+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-01T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:40.755+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.755+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:54:40.801+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:40.801+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-08-15 00:00:00+00:00, run_after=2021-08-16 00:00:00+00:00
[2025-01-14T19:54:40.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 1.133 seconds
[2025-01-14T19:54:45.365+0000] {processor.py:186} INFO - Started process (PID=5728) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:54:45.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:54:45.380+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:45.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:54:45.432+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:54:45.587+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:45.586+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-07-30T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:45.791+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:45.793+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.330029+00:00 end:2025-01-14 19:54:45.782775+00:00 duration:29.452746
[2025-01-14T19:54:45.794+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-07-30 00:00:00+00:00: scheduled__2021-07-30T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:38.608584+00:00. externally triggered: False>
[2025-01-14T19:54:45.794+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-07-30T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:45.795+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:45.795+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-07-30T00:00:00+00:00, execution_date=20210730T000000, start_date=20250114T195416, end_date=20250114T195445
[2025-01-14T19:54:45.921+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:45.921+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-07-30T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:45.930+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:45.929+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-13T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:45.995+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:45.997+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.332689+00:00 end:2025-01-14 19:54:45.995079+00:00 duration:29.66239
[2025-01-14T19:54:45.998+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-13 00:00:00+00:00: scheduled__2021-08-13T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:40.214243+00:00. externally triggered: False>
[2025-01-14T19:54:45.999+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-13T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.001+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.000+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-13T00:00:00+00:00, execution_date=20210813T000000, start_date=20250114T195416, end_date=20250114T195445
[2025-01-14T19:54:46.016+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.016+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-13T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:46.022+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.021+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-04T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.044+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:46.044+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.345631+00:00 end:2025-01-14 19:54:46.043681+00:00 duration:29.69805
[2025-01-14T19:54:46.045+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-04 00:00:00+00:00: scheduled__2021-08-04T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:39.017622+00:00. externally triggered: False>
[2025-01-14T19:54:46.047+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-04T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.048+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.047+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-04T00:00:00+00:00, execution_date=20210804T000000, start_date=20250114T195416, end_date=20250114T195446
[2025-01-14T19:54:46.058+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.057+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-04T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:46.062+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.061+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-05T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.084+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:46.084+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.641689+00:00 end:2025-01-14 19:54:46.083752+00:00 duration:29.442063
[2025-01-14T19:54:46.085+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-05 00:00:00+00:00: scheduled__2021-08-05T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:39.089545+00:00. externally triggered: False>
[2025-01-14T19:54:46.086+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-05T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.087+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.086+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-05T00:00:00+00:00, execution_date=20210805T000000, start_date=20250114T195416, end_date=20250114T195446
[2025-01-14T19:54:46.102+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.102+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-05T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:46.106+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.106+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-07T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.133+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:46.134+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.245625+00:00 end:2025-01-14 19:54:46.132575+00:00 duration:29.88695
[2025-01-14T19:54:46.135+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-07 00:00:00+00:00: scheduled__2021-08-07T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:39.247359+00:00. externally triggered: False>
[2025-01-14T19:54:46.136+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-07T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.142+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.139+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-07T00:00:00+00:00, execution_date=20210807T000000, start_date=20250114T195416, end_date=20250114T195446
[2025-01-14T19:54:46.154+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.153+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-07T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:46.158+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.157+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-12T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.178+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:46.179+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.374639+00:00 end:2025-01-14 19:54:46.177518+00:00 duration:29.802879
[2025-01-14T19:54:46.180+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-12 00:00:00+00:00: scheduled__2021-08-12T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:39.993668+00:00. externally triggered: False>
[2025-01-14T19:54:46.180+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-12T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.181+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.181+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-12T00:00:00+00:00, execution_date=20210812T000000, start_date=20250114T195416, end_date=20250114T195446
[2025-01-14T19:54:46.198+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.197+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-12T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:46.202+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.202+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-09T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.225+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:46.226+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.627093+00:00 end:2025-01-14 19:54:46.225106+00:00 duration:29.598013
[2025-01-14T19:54:46.227+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-09 00:00:00+00:00: scheduled__2021-08-09T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:39.471301+00:00. externally triggered: False>
[2025-01-14T19:54:46.227+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-09T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.232+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.231+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-09T00:00:00+00:00, execution_date=20210809T000000, start_date=20250114T195416, end_date=20250114T195446
[2025-01-14T19:54:46.245+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.244+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-09T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:46.250+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.250+0000] {taskinstance.py:3313} ERROR - {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-11T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.277+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-14T19:54:46.278+0000] {logging_mixin.py:190} INFO - Task start:2025-01-14 19:54:16.613460+00:00 end:2025-01-14 19:54:46.277413+00:00 duration:29.663953
[2025-01-14T19:54:46.280+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): first_task> dag:<DAG: first_dag> dagrun:<DagRun first_dag @ 2021-08-11 00:00:00+00:00: scheduled__2021-08-11T00:00:00+00:00, state:running, queued_at: 2025-01-14 19:53:39.749533+00:00. externally triggered: False>
[2025-01-14T19:54:46.281+0000] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'first_dag', 'Task Id': 'first_task', 'Run Id': 'scheduled__2021-08-11T00:00:00+00:00', 'Hostname': '761181778a19'}
[2025-01-14T19:54:46.282+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.282+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=first_dag, task_id=first_task, run_id=scheduled__2021-08-11T00:00:00+00:00, execution_date=20210811T000000, start_date=20250114T195416, end_date=20250114T195446
[2025-01-14T19:54:46.295+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.294+0000] {processor.py:876} INFO - Executed callback for <TaskInstance: first_dag.first_task scheduled__2021-08-11T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-14T19:54:46.378+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:54:46.378+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:54:46.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 1.193 seconds
[2025-01-14T19:55:17.227+0000] {processor.py:186} INFO - Started process (PID=6068) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:55:17.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:55:17.236+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:55:17.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:55:17.263+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:55:17.296+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:55:17.295+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:55:17.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.230 seconds
[2025-01-14T19:55:47.634+0000] {processor.py:186} INFO - Started process (PID=6423) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:55:47.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:55:47.638+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:55:47.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:55:47.664+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:55:47.689+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:55:47.688+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:55:47.730+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:55:47.730+0000] {dag.py:4180} INFO - Setting next_dagrun for first_dag to 2021-09-10 00:00:00+00:00, run_after=2021-09-11 00:00:00+00:00
[2025-01-14T19:55:47.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.134 seconds
[2025-01-14T19:56:18.454+0000] {processor.py:186} INFO - Started process (PID=6731) to work on /opt/airflow/dags/first_dag.py
[2025-01-14T19:56:18.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/first_dag.py for tasks to queue
[2025-01-14T19:56:18.459+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:56:18.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/first_dag.py
[2025-01-14T19:56:18.483+0000] {processor.py:925} INFO - DAG(s) 'first_dag' retrieved from /opt/airflow/dags/first_dag.py
[2025-01-14T19:56:18.514+0000] {logging_mixin.py:190} INFO - [2025-01-14T19:56:18.513+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-14T19:56:18.577+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/first_dag.py took 0.134 seconds
