[2025-02-02T13:22:40.257+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:22:40.273+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:22:40.283+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:22:40.284+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:22:40.343+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T13:22:40.349+0000] {standard_task_runner.py:72} INFO - Started process 263 to run task
[2025-02-02T13:22:40.355+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmphrq8gfit']
[2025-02-02T13:22:40.359+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T13:22:40.412+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host e6ed12b0dfa5
[2025-02-02T13:22:40.507+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T13:22:40.509+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:22:42.768+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:22:42.769+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:22:44.590+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:22:44.602+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:22:44.603+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T132240, end_date=20250202T132244
[2025-02-02T13:22:44.655+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:22:44.680+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:22:44.682+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:36:31.014+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:36:31.025+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:36:31.031+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:36:31.031+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:36:31.039+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T13:36:31.043+0000] {standard_task_runner.py:72} INFO - Started process 197 to run task
[2025-02-02T13:36:31.045+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpsfcr62fy']
[2025-02-02T13:36:31.047+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T13:36:31.079+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 64f2a5764477
[2025-02-02T13:36:31.137+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T13:36:31.138+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:36:33.268+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:36:33.269+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:36:33.630+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:36:33.637+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:36:33.638+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T133631, end_date=20250202T133633
[2025-02-02T13:36:33.665+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:36:33.684+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:36:33.686+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:42:28.212+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:42:28.226+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:42:28.233+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:42:28.234+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:42:28.244+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T13:42:28.248+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T13:42:28.251+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpzt4u03xc']
[2025-02-02T13:42:28.253+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T13:42:28.288+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 94cf105fca6e
[2025-02-02T13:42:28.350+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T13:42:28.351+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:42:35.709+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:42:35.710+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:42:36.078+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:42:36.085+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:42:36.086+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T134228, end_date=20250202T134236
[2025-02-02T13:42:36.123+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:42:36.140+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:42:36.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:46:19.553+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:46:19.566+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:46:19.572+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:46:19.573+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:46:19.583+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T13:46:19.587+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T13:46:19.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpzq5codqe']
[2025-02-02T13:46:19.592+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T13:46:19.626+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 774492c58bf0
[2025-02-02T13:46:19.692+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T13:46:19.694+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:46:23.496+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:46:23.497+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:46:23.853+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:46:23.861+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:46:23.862+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T134619, end_date=20250202T134623
[2025-02-02T13:46:23.896+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:46:23.915+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:46:23.917+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T13:57:59.925+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T13:57:59.937+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:57:59.944+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T13:57:59.945+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T13:57:59.953+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T13:57:59.957+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T13:57:59.960+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp_erjak_y']
[2025-02-02T13:57:59.962+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T13:57:59.997+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host f0b94dd433bd
[2025-02-02T13:58:00.061+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T13:58:00.062+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T13:58:04.898+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T13:58:04.899+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T13:58:05.258+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T13:58:05.265+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T13:58:05.266+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T135759, end_date=20250202T135805
[2025-02-02T13:58:05.298+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T13:58:05.314+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T13:58:05.316+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:03:54.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:03:54.845+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:03:54.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:03:54.851+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:03:54.860+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T14:03:54.864+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T14:03:54.866+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp4zf5b47i']
[2025-02-02T14:03:54.868+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T14:03:54.902+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 5ab92388ff22
[2025-02-02T14:03:54.967+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T14:03:54.968+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:04:00.246+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:04:00.247+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:04:00.624+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:04:00.631+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:04:00.632+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T140354, end_date=20250202T140400
[2025-02-02T14:04:00.653+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:04:00.669+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:04:00.671+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:25:01.924+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:25:01.937+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:25:01.944+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:25:01.945+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:25:01.955+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T14:25:01.959+0000] {standard_task_runner.py:72} INFO - Started process 198 to run task
[2025-02-02T14:25:01.961+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpsn6omfgh']
[2025-02-02T14:25:01.963+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T14:25:01.996+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 26561cd8ae45
[2025-02-02T14:25:02.054+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T14:25:02.055+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:25:05.705+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:25:05.706+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:25:06.085+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:25:06.095+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:25:06.096+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T142501, end_date=20250202T142506
[2025-02-02T14:25:06.147+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:25:06.165+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:25:06.167+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:29:50.554+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:29:50.570+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:29:50.579+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:29:50.580+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:29:50.592+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T14:29:50.597+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T14:29:50.599+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpb3a7ml4a']
[2025-02-02T14:29:50.603+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T14:29:50.652+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host a499fcfb67cb
[2025-02-02T14:29:50.719+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T14:29:50.720+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:29:54.612+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:29:54.613+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:29:55.030+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:29:55.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:29:55.040+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T142950, end_date=20250202T142955
[2025-02-02T14:29:55.068+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:29:55.087+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:29:55.090+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:34:47.263+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:34:47.276+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:34:47.284+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:34:47.285+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:34:47.294+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T14:34:47.299+0000] {standard_task_runner.py:72} INFO - Started process 201 to run task
[2025-02-02T14:34:47.301+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpt1_g9j3v']
[2025-02-02T14:34:47.303+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T14:34:47.343+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host be62f1cf8682
[2025-02-02T14:34:47.429+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T14:34:47.430+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:34:51.272+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:34:51.273+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:34:51.657+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:34:51.665+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:34:51.666+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T143447, end_date=20250202T143451
[2025-02-02T14:34:51.690+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:34:51.709+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:34:51.713+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:46:06.865+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:46:06.878+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:46:06.885+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:46:06.886+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:46:06.896+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T14:46:06.900+0000] {standard_task_runner.py:72} INFO - Started process 208 to run task
[2025-02-02T14:46:06.903+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp3tx1grr5']
[2025-02-02T14:46:06.905+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T14:46:06.940+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 63894a7c3fe6
[2025-02-02T14:46:07.001+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T14:46:07.003+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:46:10.546+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:46:10.547+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:46:10.886+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:46:10.892+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:46:10.893+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T144606, end_date=20250202T144610
[2025-02-02T14:46:10.933+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:46:10.953+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:46:10.955+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T14:58:22.259+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:58:22.273+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:58:22.280+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T14:58:22.281+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T14:58:22.292+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T14:58:22.296+0000] {standard_task_runner.py:72} INFO - Started process 197 to run task
[2025-02-02T14:58:22.298+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpkg292plg']
[2025-02-02T14:58:22.300+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T14:58:22.340+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host a75ab04d6f73
[2025-02-02T14:58:22.416+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T14:58:22.417+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:58:27.451+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T14:58:27.452+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T14:58:27.843+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:58:27.851+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:58:27.852+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T145822, end_date=20250202T145827
[2025-02-02T14:58:27.888+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T14:58:27.910+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:58:27.912+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T15:17:34.298+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T15:17:34.312+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T15:17:34.320+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T15:17:34.321+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T15:17:34.331+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T15:17:34.335+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T15:17:34.338+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpldz0j9cm']
[2025-02-02T15:17:34.340+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T15:17:34.377+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host d42d69d5511c
[2025-02-02T15:17:34.440+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T15:17:34.441+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T15:17:38.316+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T15:17:38.317+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T15:17:38.657+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T15:17:38.665+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T15:17:38.665+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T151734, end_date=20250202T151738
[2025-02-02T15:17:38.684+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T15:17:38.701+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T15:17:38.703+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T15:51:40.290+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T15:51:40.303+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T15:51:40.308+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T15:51:40.309+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T15:51:40.318+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T15:51:40.322+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T15:51:40.324+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpzdd7px_s']
[2025-02-02T15:51:40.326+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T15:51:40.358+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 7bf4a44673c6
[2025-02-02T15:51:40.415+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T15:51:40.416+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T15:51:44.256+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T15:51:44.257+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T15:51:44.609+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T15:51:44.616+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T15:51:44.617+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T155140, end_date=20250202T155144
[2025-02-02T15:51:44.671+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T15:51:44.691+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T15:51:44.693+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T16:03:33.477+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T16:03:33.491+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T16:03:33.497+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T16:03:33.498+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T16:03:33.509+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T16:03:33.513+0000] {standard_task_runner.py:72} INFO - Started process 207 to run task
[2025-02-02T16:03:33.516+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp3qe_vxup']
[2025-02-02T16:03:33.518+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T16:03:33.555+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 4061bda98b6f
[2025-02-02T16:03:33.629+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T16:03:33.630+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T16:03:35.775+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T16:03:35.776+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T16:03:36.151+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T16:03:36.158+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T16:03:36.159+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T160333, end_date=20250202T160336
[2025-02-02T16:03:36.177+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T16:03:36.194+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T16:03:36.196+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T17:16:41.206+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T17:16:41.218+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T17:16:41.224+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T17:16:41.225+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T17:16:41.233+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T17:16:41.237+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T17:16:41.240+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpbv4kx9wb']
[2025-02-02T17:16:41.242+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T17:16:41.280+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 17d6b2523ddc
[2025-02-02T17:16:41.342+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T17:16:41.344+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T17:16:45.060+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T17:16:45.061+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T17:16:45.429+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T17:16:45.436+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T17:16:45.437+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T171641, end_date=20250202T171645
[2025-02-02T17:16:45.466+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T17:16:45.484+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T17:16:45.486+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T17:25:17.664+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T17:25:17.678+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T17:25:17.684+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T17:25:17.685+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T17:25:17.694+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T17:25:17.699+0000] {standard_task_runner.py:72} INFO - Started process 197 to run task
[2025-02-02T17:25:17.701+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp4f6f2d42']
[2025-02-02T17:25:17.703+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T17:25:17.738+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 282dd463bdb8
[2025-02-02T17:25:17.797+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T17:25:17.799+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T17:25:22.721+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T17:25:22.722+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T17:25:23.107+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T17:25:23.115+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T17:25:23.116+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T172517, end_date=20250202T172523
[2025-02-02T17:25:23.162+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T17:25:23.181+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T17:25:23.183+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T18:21:27.838+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T18:21:27.853+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T18:21:27.861+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T18:21:27.862+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T18:21:27.873+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T18:21:27.877+0000] {standard_task_runner.py:72} INFO - Started process 207 to run task
[2025-02-02T18:21:27.880+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp9k6_1qwd']
[2025-02-02T18:21:27.882+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask save_to_minio
[2025-02-02T18:21:27.926+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 15904aeddad7
[2025-02-02T18:21:27.991+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T18:21:27.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T18:21:31.289+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T18:21:31.291+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T18:21:31.693+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T18:21:31.702+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T18:21:31.703+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T182127, end_date=20250202T182131
[2025-02-02T18:21:31.745+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T18:21:31.765+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T18:21:31.767+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T19:19:50.431+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T19:19:50.442+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T19:19:50.448+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T19:19:50.449+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T19:19:50.457+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T19:19:50.461+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T19:19:50.463+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp2pniqwd3']
[2025-02-02T19:19:50.465+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T19:19:50.502+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host dfbcbb9a3a68
[2025-02-02T19:19:50.570+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T19:19:50.571+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T19:19:53.899+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T19:19:53.900+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T19:19:54.298+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T19:19:54.308+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T19:19:54.309+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T191950, end_date=20250202T191954
[2025-02-02T19:19:54.369+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T19:19:54.380+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T19:52:54.680+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T19:52:54.694+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T19:52:54.702+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T19:52:54.704+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T19:52:54.714+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T19:52:54.720+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T19:52:54.722+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp54exja45']
[2025-02-02T19:52:54.725+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T19:52:54.777+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host cc19208c71dd
[2025-02-02T19:52:54.868+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T19:52:54.870+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T19:52:57.935+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T19:52:57.937+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T19:52:58.384+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T19:52:58.393+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T19:52:58.394+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T195254, end_date=20250202T195258
[2025-02-02T19:52:58.428+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T19:52:58.449+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T19:52:58.451+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T19:55:51.931+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T19:55:51.943+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T19:55:51.949+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T19:55:51.951+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T19:55:51.960+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T19:55:51.964+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T19:55:51.967+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpvz7djmhh']
[2025-02-02T19:55:51.969+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T19:55:52.004+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host ad5c63f64f40
[2025-02-02T19:55:52.066+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T19:55:52.067+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T19:55:54.778+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T19:55:54.779+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T19:55:55.195+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T19:55:55.204+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T19:55:55.205+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T195551, end_date=20250202T195555
[2025-02-02T19:55:55.231+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T19:55:55.250+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T19:55:55.252+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:07:28.013+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:07:28.025+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:07:28.030+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:07:28.031+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:07:28.039+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T20:07:28.043+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T20:07:28.045+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpx296o4c9']
[2025-02-02T20:07:28.047+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T20:07:28.078+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 6df1dc328a9b
[2025-02-02T20:07:28.134+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T20:07:28.135+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:07:30.815+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:07:30.816+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:07:31.260+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:07:31.268+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:07:31.269+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T200728, end_date=20250202T200731
[2025-02-02T20:07:31.309+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:07:31.327+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:07:31.329+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:15:28.483+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:15:28.498+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:15:28.505+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:15:28.506+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:15:28.516+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T20:15:28.521+0000] {standard_task_runner.py:72} INFO - Started process 196 to run task
[2025-02-02T20:15:28.524+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpidqyl5yj']
[2025-02-02T20:15:28.526+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T20:15:28.568+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host b0b992709001
[2025-02-02T20:15:28.636+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T20:15:28.638+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:15:31.301+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:15:31.302+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:15:31.658+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:15:31.666+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:15:31.667+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T201528, end_date=20250202T201531
[2025-02-02T20:15:31.708+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:15:31.723+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:15:31.726+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:35:15.554+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:35:15.567+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:35:15.573+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:35:15.573+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:35:15.582+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T20:35:15.586+0000] {standard_task_runner.py:72} INFO - Started process 567 to run task
[2025-02-02T20:35:15.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp1kxpe6lh']
[2025-02-02T20:35:15.591+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_to_minio
[2025-02-02T20:35:15.622+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 0abbc615c48a
[2025-02-02T20:35:15.682+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T20:35:15.683+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:35:18.350+0000] {base_aws.py:603} WARNING - Unable to find AWS Connection ID 'minio_conn', switching to empty.
[2025-02-02T20:35:18.351+0000] {base_aws.py:177} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-02-02T20:35:18.747+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 21, in save_to_minio
    s3_hook.load_string(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 152, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 125, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1197, in load_string
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1280, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 135, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 158, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/upload.py", line 762, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 197, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-02-02T20:35:18.758+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T203515, end_date=20250202T203518
[2025-02-02T20:35:18.769+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:35:18.770+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task save_to_minio (Unable to locate credentials; 567)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_pipeline.py", line 21, in save_to_minio
    s3_hook.load_string(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 152, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 125, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1197, in load_string
    self._upload_file_obj(f, key, bucket_name, replace, encrypt, acl_policy)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1280, in _upload_file_obj
    client.upload_fileobj(
  File "/home/airflow/.local/lib/python3.11/site-packages/boto3/s3/inject.py", line 642, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/futures.py", line 264, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 135, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/tasks.py", line 158, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/s3transfer/upload.py", line 762, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1005, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1029, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 132, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 197, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-02-02T20:35:18.812+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-02T20:35:18.827+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:35:18.829+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:40:34.999+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:40:35.013+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:40:35.021+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:40:35.022+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:40:35.032+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T20:40:35.038+0000] {standard_task_runner.py:72} INFO - Started process 279 to run task
[2025-02-02T20:40:35.040+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmprr65xwto']
[2025-02-02T20:40:35.042+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask save_to_minio
[2025-02-02T20:40:35.080+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 7ed9c07bce51
[2025-02-02T20:40:35.136+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T20:40:35.137+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:40:39.673+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:40:39.674+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:40:40.041+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:40:40.048+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:40:40.049+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T204035, end_date=20250202T204040
[2025-02-02T20:40:40.067+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:40:40.081+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:40:40.083+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-02T20:45:08.742+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T20:45:08.755+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:45:08.763+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-02T20:45:08.764+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-02T20:45:08.776+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-02T20:45:08.780+0000] {standard_task_runner.py:72} INFO - Started process 480 to run task
[2025-02-02T20:45:08.783+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmpxwym9ke2']
[2025-02-02T20:45:08.786+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask save_to_minio
[2025-02-02T20:45:08.828+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 12998e952c77
[2025-02-02T20:45:08.893+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-02T20:45:08.894+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T20:45:12.324+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-02T20:45:12.325+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-02T20:45:14.533+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T20:45:14.544+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T20:45:14.545+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250202T204508, end_date=20250202T204514
[2025-02-02T20:45:14.601+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T20:45:14.621+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T20:45:14.626+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-04T20:15:57.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T20:15:57.475+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-04T20:15:57.483+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-02-04T20:15:57.485+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-04T20:15:57.495+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): save_to_minio> on 2025-01-27 00:00:00+00:00
[2025-02-04T20:15:57.501+0000] {standard_task_runner.py:72} INFO - Started process 1661 to run task
[2025-02-04T20:15:57.504+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'save_to_minio', 'save_to_minio', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline.py', '--cfg-path', '/tmp/tmp_j1jpvx9']
[2025-02-04T20:15:57.507+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask save_to_minio
[2025-02-04T20:15:57.557+0000] {task_command.py:467} INFO - Running <TaskInstance: save_to_minio.save_to_minio scheduled__2025-01-27T00:00:00+00:00 [running]> on host 7ffbfde90b16
[2025-02-04T20:15:57.626+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andrewsis' AIRFLOW_CTX_DAG_ID='save_to_minio' AIRFLOW_CTX_TASK_ID='save_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-02-04T20:15:57.628+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T20:16:00.406+0000] {base.py:84} INFO - Retrieving connection 'minio_conn'
[2025-02-04T20:16:00.407+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-04T20:16:01.598+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-04T20:16:01.606+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T20:16:01.607+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=save_to_minio, task_id=save_to_minio, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250204T201557, end_date=20250204T201601
[2025-02-04T20:16:01.650+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T20:16:01.666+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-04T20:16:01.668+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
